### PR TITLE
Prevent executing queries twice

### LINKED ISSUE #9: "mutate" method of Mutation executes twice.
dependencies
```
Django==2.2.6
graphene-django==2.5.0
django-debug-toolbar==2.0
django-graphiql-debug-toolbar==0.1.4
```

code
```

class CreateFavourite(graphene.Mutation):
    class Arguments:
        id = graphene.ID(required=True)

    ok = graphene.Boolean()

    @staticmethod
    def mutate(_, info, id):
        print("test")
        return CreateFavourite(ok=True)
```

log 
```
System check identified no issues (0 silenced).
October 11, 2019 - 15:59:58
Django version 2.2.6, using settings 'app.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
test
test
[11/Oct/2019 15:59:59] "POST /api/graphql/ HTTP/1.0" 200 155
```

### PR DESCRIPTION
**Pull request by bellini666**
Fix #9 

I didn't want to rewrite the whole debug toolbar's logic so I wrote this to monkey patched the toolbar to be able to retrieve it after super is called, that way we don't need to instantiate another toolbar and process the response again.

### CODE REVIEW

**Comment by bellini666** [comment]
@flavors any chance to get this reviewed?

**Comment by vramos1** [comment]
please could it be reviewed? It could be very usefull, im facing the same problem here

**Comment by diegobordeu** [comment]
same problem here!! hopefully this PR reviewed soon !!!

**Comment by jrd** [comment]
Can this PR get merged please?

As of now, the debug toolbar is unusable with graphql when making mutation requests.
It's slower for query requests without impact, but it has HUGE impact when doing mutations (create, update, …).

The debug toolbar is supposed to help, not create more problems…

**Review by vberlier — APPROVED** [review]
Patiently waiting for this to be merged :eyes: :crossed_fingers:

**Comment by mohit-deepsource** [comment]
@mongkok Please take a look at this

**Comment by BioRazor** [comment]
I have the same problem, I wasted hours looking for what it was.

Our friend DebugToolbar instead of solving problems generated a new one. I will wait for this PR!

**Comment by eikichi18** [comment]
@mongkok Please merge this PR

**Comment by mongkok** [comment]
Thanks for this PR, monkey patch is the best approach.

The DebugToolbar created using `functools.partial` does not allow class methods, e.g. `DebugToolbar.is_toolbar_request()`,  I will add minor changes to support new django-debug-toolbar releases.

@bellini666 thanks for your help here and for keeping this package alive.

**Comment by bellini666** [comment]
Thanks for mergint and releasing a new working version @mongkok  :)

**Pull request merged**
